# see https://github.com/linkml/schemasheets/blob/main/.github/workflows/main.yaml

name: Check Pull Request

# Controls when the action will run.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        python-version: [ "3.10", "3.11", "3.12", "3.13", "3.14" ]

    runs-on: ${{ matrix.os }}

    steps:

      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      #----------------------------------------------
      #              install uv
      #----------------------------------------------
      - name: Install uv
        uses: astral-sh/setup-uv@v6

      #----------------------------------------------
      #       load cached venv if cache exists
      #----------------------------------------------
      - name: Load cached venv
        id: cached-uv-dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/uv.lock') }}

      #----------------------------------------------
      #              install dependencies
      #----------------------------------------------
      - name: Install dependencies
        run: uv sync

      - name: Run test suite
        run: uv run pytest tests/

      - name: Check project dependencies
        run: make check-dependencies
